### ISSUE TITLE
Add examples on how to use with different Cloud Provider's Container Registries with OIDC

### ISSUE THREAD

**Issue by maximilianbraun** [open-component-model/ocm-action#11] opened 2024-08-13 07:54 UTC
it would be great to have a couple fo usage examples, which allows simple use of the actions, without manual credential rotation, with a cloud providers OCI registry. 

Start should be Google Artifact repository, as this is what the Gardener team uses, others have a lower priority.

ie. how does a workflow look like, when used with
* https://github.com/google-github-actions/auth
* https://github.com/aws-actions/configure-aws-credentials
* https://github.com/Azure/login
* https://gcr.io (eventually already present as Github / Github actions ...)

**Comment by morri-son** [comment] 2024-10-18 10:13
duplicate of https://github.com/open-component-model/ocm-project/issues/253

**Closed as completed by morri-son** 2024-10-18 10:13 UTC
